$(TARGET): $(OBJS)
	$(CXX) $(CXX_FLAGS) $(OBJS) $(LINK) $(LIBRARY) -o $@

$(OBJS):$(OBJ_DIR)/%.o:%.cpp | $(OBJ_DIR)
	$(CXX) $(CXX_FLAGS) $< -c -o $@

$(DEPS): $(OBJ_DIR)/.deps/%.d:%.cpp | $(DEPS_DIR)
	/bin/bash -ec '$(CC) -MM $(CXX_FLAGS) $< | $(PERL) -e '\''while(<>){s/^(.*)\.o:/$(subst /,\/,$(OBJ_DIR))\/$$1.o $(subst /,\/,$(OBJ_DIR))\/.deps\/$$1.d:/g;print;}'\''> $@'

$(DEPS_DIR): | $(OBJ_SUBDIRS)
	mkdir -p $(DEPS_DIR)

$(OBJ_SUBDIRS): | $(OBJ_DIR)
	mkdir -p $(OBJ_SUBDIRS)

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

clean:
	rm -rf $(TARGET) $(OBJS)
	rm -rf $(DEPS)

-include $(DEPS)

